# Ansible playbook to create a Rackspace Cloud Server and install Magento.
# After server is created it will use rax_adminpass and install packages.
# Change file rax.py with your username and api_key for auth.
# Run with: ansible-playbook -i hosts.yml rax-magento.yml -vvv
# For image and flavor list check file lists.txt

---
- name: Build environment
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Server create request
      local_action:
        module: rax
        credentials: rax.py
        name: magento
        flavor: performance1-1
        image: 41e59c5f-530b-423c-86ec-13b23de49288
        disk_config: manual
        networks:
          - public
          - private
        region: ORD
        state: present
        wait: yes
      register: rax

    - name: Add servers to web host group
      local_action:
        module: add_host
        hostname: "{{ item.name }}"
        ansible_ssh_host: "{{ item.rax_accessipv4 }}"
        ansible_ssh_pass: "{{ item.rax_adminpass }}"
        ansible_ssh_user: root
        groupname: web
      with_items: rax.instances
      when: rax.action == 'create'

- name: Install magento, MySQL, httpd, PHP and Varnish
  hosts: web

  roles:
    - common
    - mysql 
    - httpd
    - php
    - magento
    - varnish